apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node'
        static_configs:
        - targets: ['node-exporter:9100']
      - job_name: 'container'
        static_configs:
        - targets: ['cadvisor:8080']
  alerting_rules.yml: |
    groups:
    - name: hostStatsAlert
      rules:
      - alert: hostMemUsageAlert
        expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes+node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes) > 0.55
        for: 1m
        labels:
          severity: page
        annotations:
            summary: "Instance {{ $labels.instance }} MEM usgae high"
            description: "{{ $labels.instance }} MEM usage above 85% (current value: {{ $value }})"
  alerts: |
    {}
  recording_rules.yml: |
    {}
  rules: |
    {}
