apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    imagePullPolicy: Always
    resources:
      requests:
        memory: "256Mi"
        cpu: "2"
      limits:
        memory: "256Mi"
        cpu: "2"
    securityContext:
      privileged: true
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
