apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/version: "1.8.0"
data:
  influxdb-password: "Your password"
  influxdb-user: "Your user"
