apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
  name: influxdb
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 30004
  selector:
    k8s-app: influxdb
